defaults:
  - _self_
  - sac

# env
env: humanoid
gradient_update: 1

# Basic setup
experiment: PEBBLE
agent_name: sac

device: cuda
seed: 19
num_envs: 10

# pretrained model path
pretrained_model_dir: "/home/sangheonlee/Desktop/PbRL_IsaacLab/tmp/pretrained_model/humanoid"
pretrained_model_step: 5000000

# training
num_train_steps: 2e6
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 10000
num_gradient_update: 1

# use alpha * env reward + beta * learned reward as reward
reward_alpha: 1
reward_beta: 1

# reward learning
max_feedback: 300
reward_batch: 10
segment: 20
activation: tanh
num_interact: 50000 # how often we label preferences
reward_lr: 0.0003
reward_update: 50
feed_type: 1
ensemble_size: 3
large_batch: 10 # in disagreement sampling, we sample reward_batch query pairs from reward_batch * large_batch query pairs
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0.1

reward_schedule: 0

max_query_save: 5e5

# logger
log_frequency: 10000
log_save_tb: true

save_model: true
save_model_freq: 100000

# hydra configuration
hydra:
  job:
    name: ${env}
  run:
    dir: ./exp/${env}/finetune_pebble/max_feedback${max_feedback}_reward_batch${reward_batch}_num_interact${num_interact}_seed${seed}
