defaults:
  - _self_
  - sac

# env
env: humanoid
gradient_update: 1

# Basic setup
experiment: PEBBLE
agent_name: sac

device: cuda
seed: 19
num_envs: 10

# pretrained model path
pretrained_model_dir: "/home/sangheonlee/Desktop/PbRL_IsaacLab/tmp/pretrained_model/humanoid_mirror"
pretrained_model_step: 5000000

# training
num_train_steps: 1e7
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 10000
num_gradient_update: 1

# use alpha * env reward + beta * learned reward as reward + gamma
reward_alpha: 0.0
reward_beta: 0.5
reward_gamma: 0.5

# reward learning
max_feedback: 800
reward_batch: 5
segment: 40
activation: tanh
num_interact: 50000 # how often we label preferences
reward_lr: 0.0003
reward_update: 3
feed_type: 3
ensemble_size: 3
large_batch: 20 # in disagreement sampling, we sample reward_batch query pairs from reward_batch * large_batch query pairs
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0.1

reward_schedule: 0

max_query_save: 1e6
reward_model_capacity: 200
mirror: false

load_reward_model: true 

# logger
log_frequency: 10000
log_save_tb: true

save_model: true
save_model_freq: 100000

# hydra configuration
hydra:
  job:
    name: ${env}
  run:
    dir: ./exp/${env}/finetune_pebble/max_feedback${max_feedback}_reward_batch${reward_batch}_num_interact${num_interact}_segment${segment}_mirror${mirror}_ru${reward_update}_seed${seed}
