defaults:
  - _self_
  - sac

# env
env: walker2d
gradient_update: 1

# Basic setup
experiment: PEBBLE
agent_name: sac

device: cuda
seed: 0
num_envs: 10

# training
num_train_steps: 5e6
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 10000
num_gradient_update: 1

# for use alpha * env reward + beta * learned reward as reward + gamma
reward_alpha: 0.0
reward_beta: 1.0
reward_gamma: 0.0


# unsupervise
num_unsup_steps: 20000
topK: 5
reset_update: 100

# reward learning
max_feedback: 300
reward_batch: 10
segment: 40
activation: tanh
num_interact: 10000 # how often we label preferences
reward_lr: 0.0003
reward_update: 50
feed_type: 2
ensemble_size: 3
large_batch: 10 # in disagreement sampling, we sample reward_batch query pairs from reward_batch * large_batch query pairs

reward_schedule: 0

max_query_save: 1e6 

reward_model_capacity: 400
mirror: true

# logger
log_frequency: 10000
log_save_tb: true

save_model: true
save_model_freq: 100000

# hydra configuration
hydra:
  job:
    name: ${env}
  run:
    dir: ./exp/${env}/pebble_humanT/max_feedback${max_feedback}_reward_batch${reward_batch}_large_batch${large_batch}_num_interact${num_interact}_feed_type${feed_type}_alpha${reward_alpha}_beta${reward_beta}_mirror${mirror}_seed${seed}
