defaults:
  - _self_
  - sac

#env
env: humanoid

# Basic setup
experiment: sac
agent_name: sac

device: cuda
seed: 20
num_envs: 10

# training
num_train_steps: 2e6 # 5e5
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 10000
num_gradient_update: 1

# unsupervise
num_unsup_steps: 20000
topK: 5
reset_update: 100

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
video_interval: 10000
video_length: 1000

save_model: true

# hydra configuration
hydra:
  job:
    name: ${env}
  run:
    dir: ./exp/${env}/sac/H${diag_gaussian_actor.hidden_dim}_L${diag_gaussian_actor.hidden_depth}_B${agent.batch_size}_tau${agent.critic_tau}/${experiment}_unsup${num_unsup_steps}_topk${topK}_${experiment}_lr${agent.actor_lr}_temp${agent.init_temperature}_seed${seed}
