defaults:
  - _self_
  - sac

#env
env: humanoid

# Basic setup
experiment: sac
agent_name: sac

device: cuda
seed: 1
num_envs: 10

# training
num_train_steps: 5e6 # 5e5
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 10000
num_gradient_update: 1

# unsupervise
num_unsup_steps: 20000
topK: 5
reset_update: 100

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
video_interval: 10000
video_length: 1000

save_model: true
save_model_freq: 5e5

# hydra configuration
hydra:
  job:
    name: ${env}
  run:
    dir: ./exp/${env}/sac/num_envs${num_envs}_seed${num_seed_steps}_unsup${num_unsup_steps}_actor_lr${agent.actor_lr}_critic_lr${agent.critic_lr}_bs${agent.alpha_lr}_seed${seed}
