defaults:
  - _self_
  - sac

# env
env: walker2d
gradient_update: 1

# Basic setup
experiment: PEBBLE
agent_name: sac

device: cuda
seed: 1
num_envs: 10

# training
num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 10000
num_gradient_update: 1

# unsupervise
num_unsup_steps: 20000
topK: 5
reset_update: 100

# reward learning
max_feedback: 200
reward_batch: 5
segment: 50
activation: tanh
num_interact: 10000 # how often we label preferences
reward_lr: 0.0003
reward_update: 50
feed_type: 1
ensemble_size: 3
large_batch: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0.1

reward_schedule: 0

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
video_interval: 10000
video_length: 1000

save_model: true

# hydra configuration
hydra:
  job:
    name: ${env}
  run:
    dir: ./exp/${env}/pebble_scriptedT/feed_type${feed_type}_max_feedback${max_feedback}_seed${seed}
